export declare const container: string;
export declare const displayC: string;
export declare const displayH: string;
export declare const firstLettersMove: string;
export declare const lastLettersMove: string;
export declare const loading: string;
export declare const logo: string;
export declare const moveLetter: string;
export declare const randomLetter: string;
