export const cdisplay: string;
export const hdisplay: string;
export const letterA: string;
export const letterB: string;
export const loading: string;
export const logo: string;
export const moveLetter: string;
export const randomLetter: string;
export const randomLetter2: string;
