export const container: string;
export const displayC: string;
export const displayH: string;
export const firstLettersMove: string;
export const lastLettersMove: string;
export const loading: string;
export const logo: string;
export const moveLetter: string;
export const randomLetter: string;
