name: Cron generate new word cron
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: create new word
        run: |
          curl --request POST \
          --url '${{ vars.NEXT_PUBLIC_API_URL_DEV }}/cron' \
          --header 'Authorization: Bearer ${{ secrets.TOKEN_API }}'